services:
  # Base de données PostgreSQL
  database:
    build: ./database
    container_name: lyceeproject-db
    environment:
      POSTGRES_DB: lyceeproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/
    networks:
      - lyceeproject-network
    restart: unless-stopped

  # Backend API Node.js
  backend:
    build: ./backend
    container_name: lyceeproject-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:password@database:5432/lyceeproject
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: lyceeproject
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: votre_jwt_secret_super_secure_ici
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - lyceeproject-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Next.js
  frontend:
    build: ./frontend
    container_name: lyceeproject-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - lyceeproject-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:

networks:
  lyceeproject-network:
    driver: bridge
