services:
  # Base de données PostgreSQL
  database:
    build: ./database
    container_name: lyceeproject-db
    environment:
      POSTGRES_DB: lyceeproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lyceeproject-network
    restart: unless-stopped

  # Backend API Node.js
  backend:
    build: ./backend
    container_name: lyceeproject-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: lyceeproject
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: votre_jwt_secret_super_secure_ici
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - lyceeproject-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React/Vite avec Nginx
  frontend:
    build: ./frontend
    container_name: lyceeproject-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - lyceeproject-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  lyceeproject-network:
    driver: bridge 